#!/bin/bash

C="src/${1:?BAD_COMMAND}"
shift

# shellcheck source=src/list
# shellcheck source=src/del
# shellcheck source=src/del-all
# shellcheck source=src/create
# shellcheck source=src/create-all
[ -e "${C}" ] && . "$C" || exit 1
