#!/bin/bash

N="${1:?NO_NAME}"
F="${2:-${N}.png}"
C="${SLACK_API_COOKI:?MISSING_COOKIE}"
O="${SLACK_API_OWNER:?MISSING_OWNER}"
T="${SLACK_API_TOKEN:?MISSING_TOKEN}"

! [ -e "${F}" ] && exit 1

A="https://${O}.slack.com/api/admin.emoji.add"
M="$(mimetype -b "$F")"

curl "$A" \
  -H "$C" \
  -H "Content-Type: $M" \
  -F filename="$F" \
  -F mode="data" \
  -F token="$T" \
  -F name="$N"
